### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by bugb** [ray-x/forgit.nvim#1]
I use Neovim 0.8.1 on Arch Linux

I have installed
- `fzf`, `fd`, `forgit` and `delta`: they work well when I run commands like: `ga`, `gd`
- `forgit.nvim` and `tpope/vim-fugitive`

 Here is how I setup your plugins:
https://github.com/bugb/dotfiles/pull/9/commits/f3b42cb5d0664314d8227fc39e014dead3f8d174

Video recording:
It does not show anything when I use any commands like: `Ga` or `Gd`
https://asciinema.org/a/TNnM86qNwEC4AB9sdprI3NVKq

**Comment by ray-x** [comment]
your dotfiles looks fine.
In your recording, there is a quick flash of the terminal window. It looks to me `Ga` command failed to run.
How about other commands, e.g. Glo

Another thing you can try is this:
in plugin folder, forgit.nvim/lua/forgit/init.lua line 70

```
  for _, cmd in ipairs(cmds) do
    -- create_cmd(cmd, 'lua require("forgit").' .. cmd:lower() .. '()')
    create_cmd(cmd, function(_)
      cmd = string.lower(cmd)
      lprint(cmd)
      local term = require('forgit.term').run
      term({ cmd = cmd, autoclose = true })
    end)
  end
 ```
Change line 70 to:
```
term({ cmd = cmd, autoclose = false })
```
that allows you to see the command line errors

**Comment by bugb** [comment]
Seems like git for `zsh` errors
![image](https://user-images.githubusercontent.com/9280412/209513324-c6d463ff-f23f-4528-b0f6-c41f4c4a2580.png)

Let me investigate it!
Thank you a lot for your quick support!

**Comment by bugb** [comment]
@ray-x, Ok, I got you, need to add this to my vim config
```
set shellcmdflag=-ic
```
https://github.com/bugb/dotfiles/pull/9/commits/e8c02779d815891c5fdf9fee5ceea16e14303f4f
Thanks for your awesome plugin!

![image](https://user-images.githubusercontent.com/9280412/209513882-1b7c2a05-dcd1-4cf4-b7b4-7fbad8206177.png)

**Comment by bugb** [comment]
Quick question if you dont mind, I saw you list `git fugitive` as a dependency, just curious, what is the purpose of it? Your plugin seems like its alternative.

**Comment by ray-x** [comment]
It is optional. If fugitive install the command will be set to `Git xxx` which uses fugitive, otherwise will use `git xxx`

**Comment by bugb** [comment]
@ray-x, ok, thank you again!
