### ISSUE TITLE
Popup displays nothing when running Glo

### ISSUE THREAD

**Issue by shaunwen** [ray-x/forgit.nvim#3]
OS: Macos Ventura 13.1 
Git:  git version 2.37.1
Neovim: Nvim Version: NVIM v0.8.1

![image](https://user-images.githubusercontent.com/4570313/210162582-db7282b7-de59-418d-ae2f-80685635f747.png)

**Comment by ray-x** [comment]
When you run `glo` comand in your project folder, does it output anything?

**Comment by shaunwen** [comment]
Hi Ray, thanks for following up, I could not really see any output when running the command, sometime, it just does a flashing, cannot even see the popup in the above screenshot. 

After a google search, got the following errors by running :messages
![image](https://user-images.githubusercontent.com/4570313/210163510-1e130ade-3de4-4e46-b6d8-a4b66941f4ce.png)

**Comment by ray-x** [comment]
Seems you are using a old version of guihua, could you update plugins?

**Comment by shaunwen** [comment]
Just updated all the plugins, it still got the issue though.

**Comment by ray-x** [comment]
Could you post the error message?
As the codes you mentioned in your error screenshot:

![image](https://user-images.githubusercontent.com/1681295/210166340-1aaffd78-0ede-4555-9d01-96311d2240ca.png)
But that line has gone.

https://github.com/ray-x/guihua.lua/blob/4459ce73db68bb3ad5ef789d03e6ea4adeeafa86/lua/guihua/floating.lua#L274

**Comment by shaunwen** [comment]
After the update of plugins, I cannot get that error same message again, but it still does not show the popup, only a flashing of the popup. Wonder any other way to get logs?

**Comment by shaunwen** [comment]
I saw you put a logging there https://github.com/ray-x/forgit.nvim/commit/a4e67d43227ab0d406c96bcefc965a22cc773c4f, so I updated the plugin again, and then run the Glo again, got the following error message:
![image](https://user-images.githubusercontent.com/4570313/210167374-48cb523d-0962-4ba5-8833-dd01fab3c27e.png)

**Comment by ray-x** [comment]
You can enable logs by set global variable:  ` _FORGIT_CFG.debug = true`
My plugin does not call fzf#install
Not sure where the message comes from.  Is it by running `Glo` ?

**Comment by shaunwen** [comment]
It could be from updating the fzf plugin. I tried adding `vim.g['_FORGIT_CFG.debug'] = true` in my lua config file, it didn't work. Not sure if I did it wrongly?

**Comment by ray-x** [comment]
The plugin does not depend on fzf.vim plugin. It uses the vim script included by fzf https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim . 

To enable log:
    `require("forgit").setup({ debug = true })`
I updated README for your reference

**Comment by shaunwen** [comment]
Great, thanks for that. I updated the config to enable debug, but I could not see the forgit.log under ~/.cache/nvim folder, I could only see a gi folder under .cache/forgit as following:
![image](https://user-images.githubusercontent.com/4570313/210189696-9690b1f1-8050-40f2-8b58-40fbe1d13691.png)

**Comment by shaunwen** [comment]
It seems it didn't apply the config properly, after reloading it, I got the following logging from ~/.cache/nvim/forgit.log
```שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 12:26:04: dir: /Users/shaun.wen/.config/nvim |1: glo
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 12:36:15: dir: /Users/shaun.wen/.config/nvim |1: glo
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 13:06:10: dir: /Users/shaun.wen/.config/nvim |1: gcb
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 13:06:15: dir: /Users/shaun.wen/.config/nvim |1: git checkout -b
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 13:07:04: dir: /Users/shaun.wen/.config/nvim |1: glo
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 13:07:07: dir: /Users/shaun.wen/.config/nvim |1: glo
שׁ  ...en/.config/nvim/plugged/forgit.nvim/lua/forgit/utils.lua:88 13:14:14: dir: /Users/shaun.wen/.config/nvim |1: glo
```

**Comment by ray-x** [comment]
Ok, it looks good
Your working directory is `~/.config/nvim` and it is a git repo. Am I right?
In your terminal, when you run `glo` in `~/.config/nvim` folder, what is the output in your terminal.

And what is your `shell` setup to in neovim? e.g. if you install forgit for zsh, is your shell set to zsh?

**Comment by shaunwen** [comment]
You are right. It is a git repo. I installed forgit as a ohmyzsh plugin. When I run `glo` in terminal it shows the fzf popup with a list of commits. If I open a terminal in neovim with the command `:term`, and run `glo` it does the same, and if I open the buffer list, I can see something like: `term://~/.config/nvim/..../bin/zsh`, by that, I believe the shell setup for neovim is already zsh?

**Comment by ray-x** [comment]
That looks all good.
So what is the error we got, blank screen? 
What are the error messages?

**Comment by shaunwen** [comment]
I could only see a flashing, nothing changes in whatever file I opened, no errors in both forgit.log and running :messages this time.

**Comment by ray-x** [comment]
Do you have minimum init.lua for me to reproduce?

**Comment by ray-x** [comment]
One other thing to check:
In your local copy of the plugin,  edit init.lua 

https://github.com/ray-x/forgit.nvim/blob/b4c76ff2c0c04498c3869c35361ded7c04d699c8/lua/forgit/init.lua#L77

Change this line to 
```
      term({ cmd = cmd, autoclose = false })
```
It will keep the terminal open and allow you to check error messages.

**Comment by shaunwen** [comment]
Thanks! After enabling that, I got the error: 
```
zsh:1: command not found: glo

[Process exited 127]
```
It seems there is something wrong with the git alias.

**Comment by ray-x** [comment]
Ok, seems in neovim term api, it failed to identify zsh setup.

What about in your vim cmd line run:
```
!zsh -c 'glo'   
```

**Comment by shaunwen** [comment]
Same error by running the above command.

**Comment by ray-x** [comment]
As there is no doc on how to install forgit in oh-my-zsh. I am not sure sure what is the best way to install it.

How about following commands
```
:!zsh -c -i 'glo'
:term glo
```

**Comment by shaunwen** [comment]
The [forgit](https://github.com/wfxr/forgit) needs to be installed as a custom plugin by the following command:
```shell
cd ~/.oh-my-zsh/custom/plugins
git clone https://github.com/wfxr/forgit
```
Then, add the string 'forgit' to plugins array in ~/.zshrc like `plugins=(git forgit z)`.

**Comment by shaunwen** [comment]
For :!zsh -c -i 'glo', the result is following:
![image](https://user-images.githubusercontent.com/4570313/210283923-ed7435f7-3408-46cc-b12d-86b1c888d59d.png)

For :term glo, I got the following:
```
zsh:1: command not found: glo

[Process exited 127]
```

**Comment by ray-x** [comment]
https://github.com/sbdchd/neoformat/issues/297#issuecomment-1250395677

But it looks to me you can not run a zsh forgit function alias inside neovim.
I have to run 
```
term zsh -i -c `glo`
```

**Comment by ray-x** [comment]
I add a new option `shell_mode` you can set it to true to see if make any difference.

**Comment by shaunwen** [comment]
Thanks! I tried out, it seems only the first time worked, then every time I run the Glo, it only shows the terminal without running any command while the terminal window aligned on the right hand side of the neovim window(overlapped the status line) as below:
![image](https://user-images.githubusercontent.com/4570313/210296926-a43a12df-2769-4d8d-90ee-dfe59f58b061.png)

**Comment by ray-x** [comment]
Yes, seems there is a bug in my commit. It should be fixed.

**Comment by shaunwen** [comment]
Thanks for the fix mate. Now the original issue for the no display of the popup should be considered fixed. Regarding the issue that forgit commands only run successfully for once and it only shows the terminal without running forgit commands from the second run onward for the same forgit command, I will file up a separate issue and push a pull request.

**Comment by shaunwen** [comment]
Thanks very much for your excellent idea and hard work for getting this plugin out, it definitely improves my productivity in the long run and more importantly development experience😄

**Comment by bugb** [comment]
@shaunwen @ray-x it seems similar to my issue https://github.com/ray-x/forgit.nvim/issues/1

**Comment by shaunwen** [comment]
Thanks for the mentioning @bugb, but it seems there has some issues by setting the shellcmdflag, e.g. https://github.com/neovim/neovim/issues/1756. In my case, it messed the up the use of fzf.vim.
